### ISSUE TITLE
Delay highlighting js call in case of multiple highlights

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#108]
From Mark:
```
Mark Oates [12:07 PM] 
Re highlighting: you may want to try a delay before invoking highlight.js if I rapidly click 3 tickboxes it makes 3 calls and suffers 3 full time to ~parse~ highlight penalties. (edited)

[12:07]  
People are likely to select multiples

[12:07]  
You'll have to experiment though to find a good trade off of waiting too long and triggering too quickly
```

**Comment by dane-johnson** [comment]
I feel like this shouldn't happen because highlighting is supposed to be a daemonic process. Maybe we have some bogeycode?

**Comment by Hopding** [comment]
I do not think this is necessary unless the highlighting results in poor performance (lag visible to user). Perhaps it does with large snippets, I'm not sure. But I've not noticed any problems with small ones.

**Comment by Hopding** [comment]
@dane-johnson Highlighting occurs when a new AST is generated, and also when filters are modified. Having to wait up to 1 second to see the result of a filter toggle results in a poor UX (in my opinion).

**Comment by dane-johnson** [comment]
But on the flipside, rapidly adding/removing filters can crash the application.

**Comment by Hopding** [comment]
Can it though? I haven't seen that happen.

**Comment by dane-johnson** [comment]
All of this information is outdated. The facts now stand as follows: 
- Clicking a filter now updates the global state instead of firing a callback
- Filters propagate down, and when new filters are selected, it fires a new highlight
- Highlighting is very fast now, faster than an average person can click
- Highlighting is throttled, so the event can't be fired back to back within a certain window (I think 300 ms)
Given all this, I am declaring this issue closed.
