### ISSUE TITLE
Optimize highlight function

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#197]
Highlighting involves multiple render passes. Should be made relatively atomic.

**Comment by Hopding** [comment]
Obviously there has been a lot of discussion about this, and there are a number of different paths this could go down. Two things I would like to suggest for this are:

1) See if the CodeMirror's [`operation`](https://codemirror.net/doc/manual.html#api) method proves to be of any use:
```
cm.operation(func: () → any) → any
    CodeMirror internally buffers changes and only updates its DOM structure after it has finished performing some operation ...
```

2) Try manually constructing and setting the inner HTML of the editor. Right now it constructs a huge (and unnecessary) number of DOM elements, because it puts _each character_ in its own `<span>`. It also may be rendering multiple times per highlight, which is, of course, a waste.

**Comment by dane-johnson** [comment]
I think I'll try for the first, seems less hacky. Will keep you all updated.

**Comment by dane-johnson** [comment]
`operation` is pretty effective
Without: `highlight(): 386.88ms`
With: `highlight(): 69.39ms`
These are both from highlighting all tokens on the large python file in the Slack channel.

**Comment by dane-johnson** [comment]
That's a 82.0642% decrease processing time.

**Comment by Hopding** [comment]
That is pretty significant! Is there any noticeable lag in the UI at all after that?

**Comment by dane-johnson** [comment]
There is, I believe it is related to the scrolling in the editor. Check out #230.

**Comment by solkaz** [comment]
If it is related to the scrolling, there is an option to change the `viewportMargin` for the CodeMirror instance so that we load more lines.

> viewportMargin: integer
Specifies the amount of lines that are rendered above and below the part of the document that's currently scrolled into view. This affects the amount of updates needed when scrolling, and the amount of work that such an update does. You should usually leave it at its default, 10. Can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents.

**Comment by solkaz** [comment]
There are also these options in the documentation:

> workTime, workDelay: number
Highlighting is done by a pseudo background-thread that will work for workTime milliseconds, and then use timeout to sleep for workDelay milliseconds. The defaults are 200 and 300, you can change these options to make the highlighting more or less aggressive.


> pollInterval: number
Indicates how quickly CodeMirror should poll its input textarea for changes (when focused). Most input is captured by events, but some things, like IME input on some browsers, don't generate events that allow CodeMirror to properly detect it. Thus, it polls. Default is 100 milliseconds.
